### ISSUE TITLE
EXC_BAD_ACCESS KERN_INVALID_ADDRESS

### ISSUE THREAD

**Issue by dcacenabes** [ryanmaxwell/UIAlertView-Blocks#14]
Hi,

I have not been able to reproduce the issue myself, but in my crashlytics reports I am getting:
EXC_BAD_ACCESS KERN_INVALID_ADDRESS at 0x0000000000000020

More preciselly:
UIAlertView+Blocks.m line 243
-[UIAlertView(Blocks) alertView:didDismissWithButtonIndex:]

Which is the line:
`id originalDelegate = objc_getAssociatedObject(self, UIAlertViewOriginalDelegateKey);`

Right now this is the top crash in my app.

**Comment by patrickbgit** [comment]
This happened to me and I was able to reproduce it with the following circumstances.
If the alert is shown from a BarButton target action, no error.
If the alert is shown from a didSelectRowAtIndexPath, error appears.

**Comment by ToccaLeee** [comment]
@umekun123  We have the save situation with you, do you have any solution ?

**Comment by umekun123** [comment]
@ToccaLeee Unfortunately not yet. :(
