### ISSUE TITLE
No longer compiles with iOS 7

### ISSUE THREAD

**Issue by MKevin3** [ryanmaxwell/UIAlertView-Blocks#19]
(notnull) and other areas not defined under iOS 7 - switched back to 0.8.1 so I can continue to use the library as I still need to support iOS 7 devices.

**Comment by ryanmaxwell** [comment]
What version of Xcode are you running?

**Comment by MKevin3** [comment]
I am using AppCode (from IntelliJ) version 3.1.5 but I also have Xcode 6.3. I did not try it under Xcode as I tend to use as little as possible. 


     On Tuesday, April 14, 2015 2:44 PM, Ryan Maxwell <notifications@github.com> wrote:
   

 What version of Xcode are you running?—

**Comment by ryanmaxwell** [comment]
AppCode will need to update their software to support the new [nullability annotations](https://developer.apple.com/swift/blog/?id=25). This is not an issue with this pod so i'm going to close it.
